In [161]:
#don't care anymore about random character, variable number of opened doors
import numpy as np
import matplotlib.pyplot as plt
import random


number_of_doors = 4     #n
number_of_opened_doors = 1          #m
number_of_closed_doors = 3 #number_of_doors - number_of_opened_doors

doors = np.tile(np.arange(number_of_doors), (4, 1))     #instead of storing the open/close goat/win chosen/unchosen information in different arrays, we store it as value in a matrix

for i in range(number_of_doors):
    doors[1][i] = "0"           #0 = goat
    doors[2][i] = "1"           #0 = closed, I start with open because it's easier to close the doors
    doors[3][i] = "0"           #0 = unchosen

winning_door = np.random.randint(0, number_of_doors)
doors[1][winning_door] = 1          #set the winning door
doors[2][winning_door] = 0          #close the winning door

chosen_door = np.random.randint(0, number_of_doors)
doors[3][chosen_door] = 1       #set the chosen door
doors[2][chosen_door] = 0          #close the chosen door




k=2     #records the number of closed doors
if winning_door == chosen_door:
    k = 1


for i in range(number_of_doors):
    if k == number_of_closed_doors:
        break
    if i == chosen_door or i == winning_door:        #don't want to count the already closed doors
        continue 
       
    doors[2][i] = 0
    k = k + 1
    

print(doors)

keeper = doors[0][chosen_door]
doors[2][chosen_door] = 1       #open the door so that the switcher doesn't see it
switcher = np.nonzero(doors[2] == 0)[0][np.random.randint(0,number_of_closed_doors-1)]    #select a random door from the closed ones (note that doors[2] == 0 returns TRUE when the door is closed)
doors[2][chosen_door] = 0       #reclose the chosen door

print(keeper, switcher)

[[0 1 2 3]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
3 1
